### ISSUE TITLE
Not compatible with Elixir 1.1

### ISSUE THREAD

**Issue by srid** [safwank/ElixirRetry#1]
```
==> elixir_retry
warning: the dependency :elixir_retry requires Elixir "~> 0.13.1" but you are running on v1.1.1
Compiled lib/retry.ex

== Compilation error on file lib/elixir_retry.ex ==
** (CompileError) lib/elixir_retry.ex:2: module Application.Behaviour is not loaded and could not be found
    (elixir) expanding macro: Kernel.use/1
    lib/elixir_retry.ex:2: ElixirRetry (module)
    (elixir) lib/kernel/parallel_compiler.ex:100: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8


== Compilation error on file lib/elixir_retry/supervisor.ex ==
** (CompileError) lib/elixir_retry/supervisor.ex:2: module Supervisor.Behaviour is not loaded and could not be found
    (elixir) expanding macro: Kernel.use/1
    lib/elixir_retry/supervisor.ex:2: ElixirRetry.Supervisor (module)
    (elixir) lib/kernel/parallel_compiler.ex:100: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8
```

**Comment by safwank** [comment]
I've merged a PR from @gotik that includes support for Elixir 1.1.
